### ISSUE TITLE
哥们 这个支持状态栏透明不

### ISSUE THREAD

**Issue by sujianqingfeng** [wangjinggithub/TitleBar#1]
如题

**Comment by wangjinggithub** [comment]
在4.4系统之前是不能修改状态栏的，只有在4.4及以上才能修改状态栏。修改方法（简单的修改方法，其他方式可以百度或者google）：
在Manifest.xml的application层中的theme中指定如下属性就可以修改：



```
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
```

这个titlebar中是暂时不能修改的。
