### ISSUE TITLE
您好，请教一下

### ISSUE THREAD

**Issue by wohui** [wangjinggithub/TitleBar#2]
您好，在xml中添加完点击函数，页面点击后报這个错，是什么原因呢，感谢解答啊~
12-08 04:24:30.837: E/AndroidRuntime(19431): java.lang.IllegalStateException: Could not find method onClickLeft(View) in a parent or ancestor Context for xxxxx:onClickxxxx attribute defined on view class android.widget.TextView with id 'tv_title_left'

**Comment by wangjinggithub** [comment]
请问你是在Activity中使用还是Fragment中使用？Activity没有什么问题的。
你是在Fragment中使用的话会有这个问题，这个TitleBar的点击事件只能在Activity中使用，如果你要在Fragment中使用的话就只能通过代码设置他的点击事件比如：TitleBar.setmTitleBarLeftListener();
